@startuml
participant Main as "ExosOO_version1"
participant BankingSystem as ":BankingSystem"
participant Account1 as "account1:Account"
participant Account2 as "account2:Account"

activate Main

Main -> BankingSystem : transfer(\n amount=50.0, \n debitAccountNumber="c1",\n creditAccountNumber="c2")
activate BankingSystem

BankingSystem -> BankingSystem : printBefore(amount,\n debitAccountNumber,\n creditAccountNumber)
activate BankingSystem
BankingSystem -> Account1 : toString()
BankingSystem -> Account2 : toString()
deactivate BankingSystem

BankingSystem -> Account1 : debit(amount)


BankingSystem -> Account2 : credit(amount)


BankingSystem -> BankingSystem : printAfter()
activate BankingSystem
BankingSystem -> Account1 : toString()
BankingSystem -> Account2 : toString()
deactivate BankingSystem

deactivate BankingSystem

deactivate Main

@enduml